# ESIOS API
https://api.esios.ree.es/

## Endpoints

**Indicators**

https://www.esios.ree.es/es/analisis

<img src="src/ESIOS-INDICADORES.png" width=400>

**Archives**

https://www.esios.ree.es/es/descargas

<img src="src/ESIOS-DESCARGAS.png" width=400>

## Install library

In [1]:
!pip install python-esios

Requirement already satisfied: python-esios in /Users/sota/Library/CloudStorage/Dropbox/4 Software Programs/2 API Wrappers/ESIOS API/1 Repository/python-esios (0.2.0)
Requirement already satisfied: requests in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from python-esios) (2.31.0)
Requirement already satisfied: pandas in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from python-esios) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from pandas->python-esios) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from pandas->python-esios) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from pandas->python-esios) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from pandas->python-esios) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from requests->python-esios) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from requests->python-esios) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from requests->python-esios) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from requests->python-esios) (2024.2.2)
Requirement already satisfied: six>=1.5 in /Users/sota/miniconda3/envs/work/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->python-esios) (1.16.0)

## Library structure

In [2]:
import esios
client = esios.ESIOSClient()

### Indicators

https://www.esios.ree.es/es/analisis

In [3]:
df = endpoint.list()
df

,name,description,short_name,id
0,Generación programada PBF Hidráulica UGH,"Es el programa de energía diario, con desglose...",Hidráulica UGH,1
1,Generación programada PBF Hidráulica no UGH,"Es el programa de energía diario, con desglose...",Hidráulica no UGH,2
...,...,...,...,...
1937,RD-L 10/2022 restricciones técnicas y mercados...,RD-L 10/2022 restricciones técnicas y mercados...,Mercado diario e intradiario,10411
1938,Precio medio ponderado de activación del servi...,Es un servicio específico de balance del sist...,Precio medio ponderado de activación del servi...,10412

### Archives

https://www.esios.ree.es/es/descargas

In [4]:
df = endpoint.archives.list()
df

,name,id,horizon,archive_type,download,date,date_times,publication_date,taxonomy_terms,vocabularies
0,REE_BalancingEnerBids,181,QM,csv,"{'name': 'REE_BalancingEnerBids', 'url': '/arc...",{'date': '2024-05-25T23:59:59.000+02:00'},[],[2024-05-25],"[{'id_taxonomy_term': 156, 'name': 'Mercados y...","[{'id_vocabulary': 20, 'name': 'Universo'}, {'..."
1,Resultado_Subasta_Mensual_POR,159,M,xls,"{'name': 'Resultado_Subasta_Mensual_POR', 'url...",{'date': '2024-05-25T23:59:59.000+02:00'},[],[2024-04-24],"[{'id_taxonomy_term': 156, 'name': 'Mercados y...","[{'id_vocabulary': 20, 'name': 'Universo'}, {'..."
...,...,...,...,...,...,...,...,...,...,...
24,totalp48,29,H,xml,"{'name': 'totalp48', 'url': '/archives/29/down...",{'date': '2024-05-25T23:59:59.000+02:00'},[2024-05-25],[2024-05-25],"[{'id_taxonomy_term': 155, 'name': 'Generación...","[{'id_vocabulary': 20, 'name': 'Universo'}, {'..."
25,totalrp48prec,27,H,xml,"{'name': 'totalrp48prec', 'url': '/archives/27...",{'date': '2024-05-25T23:59:59.000+02:00'},[2024-05-25],[2024-05-25],"[{'id_taxonomy_term': 156, 'name': 'Mercados y...","[{'id_vocabulary': 20, 'name': 'Universo'}, {'..."

In [5]:
df = endpoint.archives.list(start='2023-01-01', end='2023-12-31')
df

,name,id,horizon,archive_type,download,date,date_times,publication_date,taxonomy_terms,vocabularies
0,C2_PrecioFinal,187,M,zip,"{'name': 'C2_PrecioFinal', 'url': '/archives/1...","{'date_type': 'datos', 'start_date': '2023-01-...","[2023-05-01, 2023-12-31]","[2023-06-23, 2024-01-10]","[{'id_taxonomy_term': 155, 'name': 'Generación...","[{'id_vocabulary': 20, 'name': 'Universo'}, {'..."
1,C5_PrecioFinal,188,M,zip,"{'name': 'C5_PrecioFinal', 'url': '/archives/1...","{'date_type': 'datos', 'start_date': '2023-01-...","[2023-02-01, 2023-06-30]","[2024-01-22, 2024-05-22]","[{'id_taxonomy_term': 155, 'name': 'Generación...","[{'id_vocabulary': 20, 'name': 'Universo'}, {'..."
...,...,...,...,...,...,...,...,...,...,...
52,totalrpdvpprec,19,D,xml,"{'name': 'totalrpdvpprec', 'url': '/archives/1...","{'date_type': 'datos', 'start_date': '2023-01-...","[2023-01-01, 2023-12-31]","[2022-12-31, 2023-12-30]","[{'id_taxonomy_term': 156, 'name': 'Mercados y...","[{'id_vocabulary': 20, 'name': 'Universo'}, {'..."
53,totalpdbf,18,D,xml,"{'name': 'totalpdbf', 'url': '/archives/18/dow...","{'date_type': 'datos', 'start_date': '2023-01-...","[2023-01-01, 2023-12-31]","[2022-12-31, 2023-12-30]","[{'id_taxonomy_term': 155, 'name': 'Generación...","[{'id_vocabulary': 20, 'name': 'Universo'}, {'..."

## Unidades

- Unidades fisicas: https://www.esios.ree.es/es/unidades-fisicas
- Unidades de programación: https://www.esios.ree.es/es/unidades-de-programacion
- Sujetos del mercado: https://www.esios.ree.es/es/sujetos-del-mercado

## Ficheros
- I3DIA: Tecnología
- IMES: [Sujeto de liquidación](https://www.esios.ree.es/es/sujetos-del-mercado)
- I90DIA: [Unidad de programación](https://www.esios.ree.es/es/unidades-de-programacion)